name: chat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  date_format: ^2.0.2
  device_info_plus: 3.0.0
  flutter_svg: ^1.0.3
  get: ^4.6.1
  get_it: ^7.6.0
  get_storage: ^2.0.2
  shared_preferences: ^2.0.12
  camera: ^0.9.0
  image_picker: ^0.8.6
  intl: ^0.17.0
  fluttertoast: ^8.0.8
  path_provider: ^2.0.9
  permission_handler: ^10.2.0
  path: ^1.8.0
  connectivity_plus: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/language/
    - assets/svg/
    - assets/icon/
    - assets/image/

  fonts:
    - family: SE Pro Display
      fonts:
        - asset: assets/fonts/SE Pro Display/SFPRODISPLAYLIGHTITALIC.OTF
          weight: 300
        - asset: assets/fonts/SE Pro Display/SFPRODISPLAYREGULAR.OTF
          weight: 400
        - asset: assets/fonts/SE Pro Display/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/SE Pro Display/SFPRODISPLAYMEDIUM.OTF
          weight: 600
        - asset: assets/fonts/SE Pro Display/SFPRODISPLAYBOLD.OTF
          weight: 700
        - asset: assets/fonts/SE Pro Display/SFPRODISPLAYBOLD.OTF
          weight: 800